try {
    console.log('ready');
    



    
    
} catch (error) {
    console.log(error);
    
}
